# Generated by Django 6.0.3 on 2026-03-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_obra', models.CharField(max_length=100)),
                ('cidade_obra', models.CharField(max_length=100)),
                ('estado_obra', models.CharField(max_length=2)),
                ('taxa_bdi', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255)),
                ('caminho_arquivo', models.TextField()),
                ('status_processamento', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='apps.projetos.projeto')),
            ],
        ),
    ]
