# Generated by Django 6.0.3 on 2026-03-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_arquivoupload_tamanho_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origem', models.CharField(default='sinapi', max_length=50)),
                ('status_mapeamento', models.CharField(default='pendente', max_length=20)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_extraidos', to='projetos.arquivoupload')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='projetos.projeto')),
            ],
        ),
    ]
