# Generated by Django 6.0.3 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_itemprojeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprojeto',
            name='origem',
            field=models.CharField(choices=[('sinapi', 'SINAPI'), ('proprio', 'Composição Própria')], default='sinapi', max_length=50),
        ),
    ]
