# Generated by Django 6.0.3 on 2026-03-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_itemprojeto_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='desc_obra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(choices=[('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('alvenaria', 'Alvenaria'), ('spda', 'SPDA'), ('combate_a_incendio', 'Combate a Incêndio'), ('null', 'Não Informado')], default='null', max_length=50),
        ),
    ]
