# Generated by Django 6.0.3 on 2026-04-01 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_projeto_tipo_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemprojeto',
            name='origem',
            field=models.CharField(choices=[('sinapi', 'SINAPI'), ('proprio', 'Composição Própria'), ('cotacao_manual', 'Cotação Manual')], default='sinapi', max_length=50),
        ),
        migrations.AddField(
            model_name='itemprojeto',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_em_projetos', to='projetos.catalogoitem'),
        ),
    ]
