# Generated by Django 6.0.3 on 2026-04-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_catalogoitem_alter_itemprojeto_origem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogoitem',
            name='quantidade',
        ),
    ]
