# Generated by Django 6.0.3 on 2026-04-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_catalogoitem_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprojeto',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_extraidos', to='projetos.arquivoupload'),
        ),
    ]
