# Generated by Django 6.0.3 on 2026-04-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_alter_itemprojeto_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tipo_projeto',
        ),
    ]
