# Generated by Django 6.0.3 on 2026-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_remove_projeto_tipo_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivoupload',
            name='caminho_arquivo',
        ),
        migrations.AddField(
            model_name='arquivoupload',
            name='memorial_calculo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivoupload',
            name='orcamento_final',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivoupload',
            name='sugestoes_sinapi',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
