# Generated by Django 6.0.3 on 2026-05-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_remove_arquivoupload_caminho_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivoupload',
            name='memorial_calculo',
        ),
        migrations.RemoveField(
            model_name='arquivoupload',
            name='orcamento_final',
        ),
        migrations.RemoveField(
            model_name='arquivoupload',
            name='sugestoes_sinapi',
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorial_calculo', models.JSONField(blank=True, null=True)),
                ('orcamento_final', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoriais', to='projetos.arquivoupload')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoriais', to='projetos.projeto')),
            ],
        ),
    ]
