# Generated by Django 6.0.3 on 2026-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_remove_arquivoupload_memorial_calculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='memorial_descritivo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
