# Generated by Django 6.0.3 on 2026-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_memorial_memorial_descritivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoupload',
            name='caminho_arquivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
